[build]
  command = "GENERATE_SOURCEMAP=false NODE_ENV=production CI=false npm run build"
  publish = "build/"

[build.environment]
  GENERATE_SOURCEMAP = "true"

[build.production.environment]
  GENERATE_SOURCEMAP = "false"